version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # image: nginx:latest
    container_name: webserver
    ports:
      - "3666:80"
    # volumes:
    #   - ./:/usr/share/nginx/html:ro
    restart: always
